#!/bin/bash
# JankyBorders configuration
# Highlight the focused window with a colored border.

borders active_color=0xffe1e3e4 \
        inactive_color=0xff494d64 \
        width=5.0 \
        hidpi=on \
        style=round
